Fix compilation error: Remove orphaned injectFixedPixelViewport() call
- Another orphaned method call found in WebViewClient.onPageFinished()
- Method was removed but call remained on line 97